Server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_regisration
    username: root
    password: Rchena@9
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
